### ISSUE TITLE
Line @ Dartmouth code review

### ISSUE THREAD

**Issue by laureldernbach** [dartmouth-cs98/21f-breeze#318]
with Sanjana Goli @sanjanagoli 2/4/22

Overall this project's code looks great! it is really well organize and easy to follow, , even with their complex data queries. My one suggestion is that they consider using functional components rather than class components as it might make the code a little easier to debug down the line. Additionally, when working with API endpoints, it can be helpful to store long links as variables to make them easy to refactor in a pinch!

**Comment by laureldernbach** [comment]
yes, we looked at the repositories bases together in person. I didn't have access to the repo to reference specific lines on github.

**Comment by timofei7** [comment]
got it. each team should have admin on their repos m, but all good
